CREATE DATABASE testingsystem1;
USE testingsystem1;

CREATE TABLE department (
	DepartmentID 		SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    DepartmentName 		VARCHAR(30) NOT NULL
);

CREATE TABLE position (
	PositionID    		SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    PositionName 		ENUM('Dev', 'Test', 'Scrum Master', 'PM') NOT NULL
);

CREATE TABLE account (
	AccountID 			SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    Email 				VARCHAR(50) NOT NULL UNIQUE, 
	Username			VARCHAR(50) NOT NULL,
    Fullname 			VARCHAR(50) NOT NULL,
    DepartmentID 		SMALLINT UNSIGNED NOT NULL,
    FOREIGN KEY (DepartmentID) REFERENCES Department (DepartmentID),
    PositionID  		SMALLINT UNSIGNED NOT NULL,
    FOREIGN KEY (PositionID ) REFERENCES Position (PositionID ),
    CreateDate 			DATETIME DEFAULT NOW()
);

CREATE TABLE `group` (
	GroupID 			SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    GroupName 			VARCHAR(50) NOT NULL UNIQUE,
    CreatorID			SMALLINT UNSIGNED NOT NULL,
    CreateDate 			DATETIME DEFAULT NOW()
);

CREATE TABLE group_account (
	GroupID					SMALLINT UNSIGNED NOT NULL,
    AccountID				SMALLINT UNSIGNED NOT NULL,
    JoinDate				DATETIME DEFAULT NOW(),
    PRIMARY KEY (GroupID,AccountID),
    FOREIGN KEY(GroupID) REFERENCES `Group`(GroupID)
);

CREATE TABLE TypeQuestion (
	TypeID 				SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    TypeName 			ENUM ('Essay', 'Mutiple-Choice') NOT NULL UNIQUE
);

CREATE TABLE CategoryQuestion (
	CategoryID 			SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    CategoryName 		NVARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE Question (
	QuestionID 			SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    Content 			VARCHAR(500) NOT NULL,
    CategoryID	 		SMALLINT UNSIGNED,
    FOREIGN KEY (CategoryID) REFERENCES CategoryQuestion (CategoryID),
    TypeID 				SMALLINT UNSIGNED NOT NULL,
    FOREIGN KEY (TypeID) REFERENCES TypeQuestion (TypeID),
    CreatorID			SMALLINT UNSIGNED NOT NULL,
    CreateDate 			DATETIME DEFAULT NOW()
);

CREATE TABLE Answer (
	AnswerID 			SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    Content 			VARCHAR(100) NOT NULL,
    QuestionID 			SMALLINT UNSIGNED NOT NULL,
    FOREIGN KEY (QuestionID) REFERENCES Question (QuestionID),
    isCorrect 			BIT DEFAULT 1
);

CREATE TABLE Exam (
	ExamID 				SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    Code 				CHAR(10) NOT NULL,
    Title 				VARCHAR(100) NOT NULL,
    CategoryID			SMALLINT UNSIGNED NOT NULL,
    Duration 			VARCHAR(10) NOT NULL,
    CreatorID			SMALLINT UNSIGNED NOT NULL,
    CreateDate 			DATETIME DEFAULT NOW(),
	FOREIGN KEY (CategoryID) REFERENCES CategoryQuestion (CategoryID) ,
    FOREIGN KEY (CreatorID) REFERENCES Account (AccountId)
);

CREATE TABLE ExamQuestion (
	ExamID 				SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    FOREIGN KEY (ExamID) REFERENCES Exam (ExamID),
    QuestionID 			SMALLINT UNSIGNED,
    FOREIGN KEY (QuestionID) REFERENCES Question (QuestionID)
);


